// Suggested exercises for the datalist; free text is still allowed.
export const COMMON_EXERCISES = [
  'Bench Press',
  'Squat',
  'Deadlift',
  'Overhead Press',
  'Barbell Row',
  'Pull-up',
  'Push-up',
  'Lat Pulldown',
  'Leg Press',
  'Leg Curl',
  'Leg Extension',
  'Bicep Curl',
  'Tricep Pushdown',
  'Dumbbell Shoulder Press',
  'Dumbbell Row',
  'Lunges',
  'Plank',
  'Running',
  'Cycling',
  'Rowing Machine',
  'Swimming',
]
