// Suggested exercises for the datalist; free text is still allowed.
export const COMMON_EXERCISES = [
  // Chest
  'Bench Press',
  'Incline Bench Press',
  'Decline Bench Press',
  'Dumbbell Bench Press',
  'Incline Dumbbell Press',
  'Dumbbell Fly',
  'Cable Fly',
  'Pec Deck',
  'Machine Chest Fly',
  'Push-up',
  'Dip',
  'Chest Press Machine',

  // Back
  'Deadlift',
  'Barbell Row',
  'Dumbbell Row',
  'Pull-up',
  'Chin-up',
  'Lat Pulldown',
  'Seated Cable Row',
  'T-Bar Row',
  'Face Pull',
  'Back Extension',
  'Straight-Arm Pulldown',
  'Inverted Row',

  // Legs
  'Squat',
  'Front Squat',
  'Leg Press',
  'Leg Curl',
  'Leg Extension',
  'Lunges',
  'Bulgarian Split Squat',
  'Romanian Deadlift',
  'Hip Thrust',
  'Calf Raise',
  'Goblet Squat',
  'Step-up',
  'Glute Bridge',
  'Seated Calf Raise',

  // Shoulders
  'Overhead Press',
  'Dumbbell Shoulder Press',
  'Arnold Press',
  'Lateral Raise',
  'Front Raise',
  'Rear Delt Fly',
  'Upright Row',
  'Shrug',
  'Cable Lateral Raise',

  // Arms
  'Bicep Curl',
  'Hammer Curl',
  'Preacher Curl',
  'Tricep Pushdown',
  'Tricep Extension',
  'Skull Crusher',
  'Close-Grip Bench Press',
  'Cable Curl',
  'Bench Dip',

  // Core
  'Plank',
  'Side Plank',
  'Crunch',
  'Sit-up',
  'Russian Twist',
  'Hanging Leg Raise',
  'Mountain Climber',
  'Cable Woodchopper',

  // Cardio
  'Walking',
  'Running',
  'Cycling',
  'Rowing',
  'Rowing Machine',
  'Swimming',
  'Stair Climber',
  'Elliptical',
  'Jump Rope',
  'Sprints',
  'Hiking',
  'Treadmill Run',
  'Stationary Bike',
  'Ski Erg',
  'Boxing',
]
